apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: patient:1.0
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              value: "patient"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
